# Generated by Django 3.2.4 on 2021-06-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='postname',
        ),
    ]
