# Generated by Django 3.2.4 on 2021-06-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_post_post_postname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='post',
        ),
    ]
