# Generated by Django 3.2.4 on 2021-06-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_postname_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='postTitle',
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
