# Generated by Django 3.2.4 on 2021-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210607_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pw',
            field=models.CharField(default='password', max_length=15),
        ),
    ]
