# Generated by Django 3.2.4 on 2021-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(max_length=120, unique=True, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='유저 이름')),
                ('user_email', models.EmailField(max_length=120, unique=True, verbose_name='유저 이메일')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 시간')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
    ]
